
server:
  port: 8080 # 监听端口
  context-path: /api/v3 # 访问路径
  tomcat:
    max-threads: 400
spring:
  profiles:
    active: local
  activemq:
    broker-url: tcp://192.168.145.150:61616
    user:
    password:
mybatis:
  config-location: classpath:mybatis-config.xml
